### ISSUE TITLE
windows10，errors about glutInit occur when I run the DeepMimic.py

### ISSUE THREAD

**Issue by GarrettZhen** [xbpeng/DeepMimic#133]
Excuse me, I also met some problems about glutInit error. When I run the DeepMimic.py, The following will occur:
Traceback (most recent call last):
  File "DeepMimic.py", line 319, in <module>
    main()
  File "DeepMimic.py", line 311, in main
    init_draw()
  File "DeepMimic.py", line 269, in init_draw
    glutInit()
  File "C:\Program Files\Python35\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Program Files\Python35\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

Cloud you help me?

**Comment by GarrettZhen** [comment]
I have solved it. When I install PyopengL, I should install the 64-bit version.
