### ISSUE TITLE
undefined symbol: _ZNK11btMultiBody12hasFixedBaseEv

### ISSUE THREAD

**Issue by sontungtran** [xbpeng/DeepMimic#158]
After installing all the required dependencies and modify the Makefile in DeepMimicCore/, I tried to run the `python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt` in Ubuntu 18.04, which led to the issue `undefined symbol: _ZN11btMultiBody22addJointTorqueMultiDofEiPKF` (Issue #82).  

After solving that issue with [this solution](https://github.com/xbpeng/DeepMimic/issues/82#issuecomment-534513934), I got this new error: `undefined symbol: _ZNK11btMultiBody12hasFixedBaseEv`

---

Traceback (most recent call last):
  File "DeepMimic.py", line 9, in <module>
    from env.deepmimic_env import DeepMimicEnv
  File "/home/tung/pj/DeepMimic/env/deepmimic_env.py", line 3, in <module>
    from DeepMimicCore import DeepMimicCore
  File "/home/tung/pj/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 13, in <module>
    from . import _DeepMimicCore
ImportError: /home/tung/pj/DeepMimic/DeepMimicCore/_DeepMimicCore.so: undefined symbol: _ZNK11btMultiBody12hasFixedBaseEv

---

The solution to previous problem `undefined symbol: _ZN11btMultiBody22addJointTorqueMultiDofEiPKF`:
https://github.com/xbpeng/DeepMimic/issues/82#issuecomment-534513934

> solved by
> 
> wget https://github.com/bulletphysics/bullet3/archive/2.88.tar.gz
> mv 2.88.tar.gz bullet3-2.88.tar.gz
> 
> tar xvzf bullet3-2.88.tar.gz
> 
> cd bullet3-2.88
> 
> sed -i 's/-DUSE_DOUBLE_PRECISION=ON/-DUSE_DOUBLE_PRECISION=OFF/g'
> 
> build_cmake_pybullet_double.sh
> 
> ./build_cmake_pybullet_double.sh
> 
> cd build_cmake
> 
> make install
> 
> cd ../..

**Comment by noshaba** [comment]
I had the same issue. This helped for me:
https://github.com/xbpeng/DeepMimic/issues/108

Turned out I had two different Bullet versions installed in two different folders.

**Comment by WilliamTambellini** [comment]
Try the new build script added in master few days ago.

**Comment by blusque** [comment]
Well, the same problem. And I also have another undefined reference that is "_ZNK11btMultiBody15isBaseKinematicEv".

**Comment by blusque** [comment]
> I had the same issue. This helped for me: [#108 (comment)](https://github.com/xbpeng/DeepMimic/issues/108#issuecomment-665538617)
> 
> Turned out I had two different Bullet versions installed in two different folders.

Thanks, but I think there's a little bit difference between the 2 problems. And I'm sorry that the solution doesn't work for me.

**Comment by zzzbbs** [comment]
> > I had the same issue. This helped for me: [#108 (comment)](https://github.com/xbpeng/DeepMimic/issues/108#issuecomment-665538617)
> > Turned out I had two different Bullet versions installed in two different folders.
> 
> Thanks, but I think there's a little bit difference between the 2 problems. And I'm sorry that the solution doesn't work for me.

sorry for the bother.Have you fixed this problem?I met the same problem of this issue too. I have tried the solution provided by other issue, but still doesn't work.

**Comment by zjuliangxun** [comment]
maybe you need to delete all files generated using the last version? To run "make clean" or "rm * .o" might help

**Comment by zzzbbs** [comment]
> maybe you need to delete all files generated using the last version? To run "make clean" or "rm * .o" might help

Thank you for your reply. I have fixed this problem by deleting all files generated using "make python", and running the new build script to automatically install all the package needed, it works finally.
