### ISSUE TITLE
unbuntu 20.04，errors about glutInit occur when I run the DeepMimic.py

### ISSUE THREAD

**Issue by Ccarrotr** [xbpeng/DeepMimic#195]
When I run DeepMimic.py, errors came out like this:`OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling.`
 I search online for the problem, but the answers are all about windows system, said that they should download 64-bit wheel for windows.But I didn't find the solution for linux. Hoping somebody can help me.
The details about the error is as follows:
`Traceback (most recent call last):
  File "DeepMimic.py", line 314, in <module>
    main()
  File "DeepMimic.py", line 306, in main
    init_draw()
  File "DeepMimic.py", line 267, in init_draw
    glutInit()  
  File "/home/liurui/anaconda3/envs/DeepMimic/lib/python3.7/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/liurui/anaconda3/envs/DeepMimic/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
`

**Comment by Ccarrotr** [comment]
I solved this problem by installing the following library package:`sudo apt-get install python3-opengl`, I guess the reason is that my opengl environment was not complete before.
