### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by noureldinalaa** [xbpeng/DeepMimic#33]
Hi , 
can you mention  in which linux version did you install this environment as i think my problem is with linux version ,i am having some troubles in the bullet installation as stated in one of the issues that can't find  
cannot find -lBulletDynamics
cannot find -lBulletCollision
when i built it i think it should be build in the src/bin and src/include but it doesn't.
i have specified a build folder and i have put it in 
Makefile in DeepMimicCore/

thanks in advance

**Comment by lyokka** [comment]
I used to encounter similar problem, I solved this problem by compile bullet in its folder, since official installation guide for bullet doesn't mention to compile something,  after compiling bullet you need to have folders like "/bullet3/build_cmake/src/BulletCollision", "/bullet3/build_cmake/src/BulletDynamics", ...

**Comment by xbpeng** [comment]
We were running it on AWS linux instances, so not sure about which version of linux that is. But maybe the installation guide for bullet can help:
https://github.com/kripken/bullet/blob/master/INSTALL

**Comment by Bervvv** [comment]
I encountered similar problem too. Though I installed bullet in both `/usr/local/include/bullet` & `/usr/include/bullet`, and indicated this path in Makefile, it always occurred `fatal error: 'btBulletDynamicsCommon.h' file not found`. I tried to modified `#include "btBulletDynamicsCommon.h"` as `#include "bullet/btBulletDynamicsCommon.h"` in `Wrold.h`, and then it seemed to work.

However, new error `fatal error: 'LinearMath/btVector3.h' file not found` occurred. I don't know how to solve it. Do you have any suggestion?

I have double check those file.h do exist in both directories.

**Comment by wangyuwei2015** [comment]
I had the same problem but after editing the Makefile in DeepMimicCore/ it disappeared. 
Specific part in Makefile:
python: $(OUT_DIRS) $(OBJ)
	swig -c++ -python DeepMimicCore.i
	$(CC) -c -g $(CFLAGS) $(INC) $(LIBS) DeepMimicCore.cpp DeepMimicCore_wrap.cxx -I$(PYTHON_INC) -L/home/yd/Documents/bullet3/build_cmake/src/BulletCollision/ -L/home/yd/Documents/bullet3/build_cmake/src/BulletDynamics -lBulletDynamics -lBulletCollision -L/home/yd/Documents/bullet3/build_cmake/src/LinearMath -lLinearMath
	$(CC) -shared $(CFLAGS) $(OBJ) $(LIBS) DeepMimicCore_wrap.o -o _DeepMimicCore.so -L$(PYTHON_LIB) -L/home/yd/Documents/bullet3/build_cmake/src/BulletCollision/ -L/home/yd/Documents/bullet3/build_cmake/src/BulletDynamics -lBulletDynamics -lBulletCollision -L/home/yd/Documents/bullet3/build_cmake/src/LinearMath -lLinearMath

 However, I think I might be wrong in this since I got new error like following.

yd@yd:~/workspace/DeepMimic$ python DeepMimic.py --arg_file args/kin_char_args.txt
  File "DeepMimic.py", line 44
    assert succ, Logger.print('Failed to load args from: ' + arg_file)
                            ^
SyntaxError: invalid syntax
yd@yd:~/workspace/DeepMimic$ python3 DeepMimic.py --arg_file args/kin_char_args.txt
Traceback (most recent call last):
  File "DeepMimic.py", line 9, in <module>
    from env.deepmimic_env import DeepMimicEnv
  File "/home/yd/workspace/DeepMimic/env/deepmimic_env.py", line 3, in <module>
    from DeepMimicCore import DeepMimicCore
  File "/home/yd/workspace/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 28, in <module>
    _DeepMimicCore = swig_import_helper()
  File "/home/yd/workspace/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 24, in swig_import_helper
    _mod = imp.load_module('_DeepMimicCore', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/yd/workspace/DeepMimic/DeepMimicCore/_DeepMimicCore.so: undefined symbol: _ZN11btMultiBody22addJointTorqueMultiDofEiPKf


Everytime I run python DeepMimic.py it shows up problem in _DeepMimicCore.so which was generated from the command "make python".

**Comment by zhaolongkzz** [comment]
If you want settings of Linux(Ubuntu) version, you could visit here [Link](https://github.com/zhaolongkzz/DeepMimic_configuration), which I offer several problem solving.
Hope it can work to you~

**Comment by xbpeng** [comment]
Thanks for putting that together. It's really helpful!
