### ISSUE TITLE
DeepMimicCore.py is not generated

### ISSUE THREAD

**Issue by kidach1** [xbpeng/DeepMimic#67]
Hi, I got only `_DeepMimicCore.pyd` without `DeepMimicCore.py` after I built DeepMimicCore.sln with the Release_Swig.

And if I try to run `DeepMimic.py`, I get this error:

```
(py36) D:\workspace\ML\DeepMimic-master1>python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt
Traceback (most recent call last):
  File "DeepMimic.py", line 9, in <module>
    from env.deepmimic_env import DeepMimicEnv
  File "D:\workspace\ML\DeepMimic-master1\env\deepmimic_env.py", line 3, in <module>
    from DeepMimicCore import DeepMimicCore
ImportError: cannot import name 'DeepMimicCore'
``` 

Could you help me?

My environmets:

```
Microsoft Windows [Version 10.0.17763.0]
Visual Studio 2017
Python 3.6
bullet3-2.87
swigwin-4.0.0
```

**Comment by xbpeng** [comment]
Was the Release_Swig build successful? This is output any errors messages when building?

**Comment by kidach1** [comment]
Yes, my build was successful.

output:

![DeepMimicCore - Microsoft Visual Studio 2019-07-06 07 58 21](https://user-images.githubusercontent.com/1152893/60747946-03f05800-9fc4-11e9-9a3d-beb4796b134e.png)

**Comment by Zju-George** [comment]
> Yes, my build was successful.
> 
> output is this:
> 
> ![DeepMimicCore - Microsoft Visual Studio 2019-07-06 07 58 21](https://user-images.githubusercontent.com/1152893/60747946-03f05800-9fc4-11e9-9a3d-beb4796b134e.png)

you probably need to specify  **PYTHON_INCLUDE** & **PYTHON_LIB** , in you output, they show nothing after **:**, note that they are echoed like in CMD you echo something. You can look into **DeepMimicCore.i**, there is a command line.
