### ISSUE TITLE
Python Fail to Import _DeepMimicCore on Windows 10

### ISSUE THREAD

**Issue by donamin** [xbpeng/DeepMimic#76]
I'm facing the same problem in Windows 10. I also tried with Bullet 2.88 but it's not solved. This is my DeepMimicCore folder after building the DeepMimicCore solution.
![image](https://user-images.githubusercontent.com/4231500/62967635-3741b600-bdbe-11e9-8f45-e922c537c67d.png)

**Comment by donamin** [comment]
Update: I tried installing Anaconda Python but didn't fix the problem. I'm building _DeepMimicCore.pyd using Visual Studio Community 2019.

**Comment by Zju-George** [comment]
#12 It may be something about missing .dll

**Comment by vkozin97** [comment]
After seemingly sucsessful build of DeepMimicCore and running the example from ReadMe I have the same problem:

`(DeepMimicEnv) C:\Users\KozinV\Documents\Android Walking\DeepMimic>python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt                                                                                                         Traceback (most recent call last):                                                                                        File "DeepMimic.py", line 9, in <module>                                                                                  from env.deepmimic_env import DeepMimicEnv                                                                            File "C:\Users\KozinV\Documents\Android Walking\DeepMimic\env\deepmimic_env.py", line 3, in <module>                      from DeepMimicCore import DeepMimicCore                                                                               File "C:\Users\KozinV\Documents\Android Walking\DeepMimic\DeepMimicCore\DeepMimicCore.py", line 13, in <module>           from . import _DeepMimicCore                                                                                        ImportError: DLL load failed: Не найден указанный модуль. `

My DeepMimicCore directory has also a package directory and a package.config file, because I used the NuGet for building the solution. Dont think that's the reason for this issue.
![image](https://user-images.githubusercontent.com/15280666/63367412-69d24c80-c384-11e9-9961-f6281c176023.png)

Have anybody already solved this?

**Comment by vkozin97** [comment]
Seems like I've resolved this particular issue. What worked for me is adding the folder containing "freeglut.dll", "glew32.dll" and "glfw3.dll" to my Path system variable

**Comment by kuochiyoug** [comment]
I tested with my project and it also has same problem. 
But I test with only include with built glew32.dll will be fine.
And now it runs nice and well!

**Comment by Wastoon** [comment]
> Update: I tried installing Anaconda Python but didn't fix the problem. I'm building _DeepMimicCore.pyd using Visual Studio Community 2019.

Hi, buddy, have you solved this problem till now? Could you do me a favor, cause I am just suffering the same problem as you. Thanks a lot!

**Comment by tinelion** [comment]
> Seems like I've resolved this particular issue. What worked for me is adding the folder containing "freeglut.dll", "glew32.dll" and "glfw3.dll" to my Path system variable

This works  for me，after do this and reboot. thanks a lot.
